export const NEWS = {
    REQUEST_NEWS: 'REQUEST_NEWS',
    REQUEST_NEWS_SUCCESS: 'REQUEST_NEWS_SUCCESS',
    REQUEST_NEWS_ERROR: 'REQUEST_NEWS_ERROR',
    ADD_SHOWN_NEWS: 'ADD_SHOWN_NEWS',
};

export const SOURCES = {
    REQUEST_SOURCES: 'REQUEST_SOURCES',
    REQUEST_SOURCES_SUCCESS: 'REQUEST_SOURCES_SUCCESS',
    REQUEST_SOURCES_ERROR: 'REQUEST_SOURCES_ERROR',
};

export const SHOW_ONLY_FROM = 'SHOW_ONLY_FROM';
