const articles = [
    {
        source: {
            id: 'techcrunch',
            name: 'TechCrunch',
        },
        author: 'Ingrid Lunden',
        title: 'VDOO secures $32M for a platform that detects and fixes vulnerabilities on IoT devices',
        description: 'Our universe of connected things is expanding by the day: the number of objects with embedded processors now exceeds the number of smartphones globally and is projected to reach some 18 billion devices by 2022. But just as that number is growing, so are the o…',
        url: 'https://techcrunch.com/2019/04/24/vdoo-secures-32m-for-a-platform-that-detects-and-fixes-vulnerabilities-on-iot-devices/',
        urlToImage: 'https://techcrunch.com/wp-content/uploads/2016/10/gettyimages-595163150.png?w=711',
        publishedAt: '2019-04-24T10:45:28Z',
        content: 'Our universe of connected things is expanding by the day: the number of objects with embedded processors now exceeds the number of smartphones globally and is projected to reach some 18 billion devices by 2022. But just as that number is growing, so are the o… [+6537 chars]',
    },
    {
        source: {
            id: 'techcrunch',
            name: 'TechCrunch',
        },
        author: 'Jake Bright',
        title: 'Drone delivery startup Zipline launches UAV medical program in Ghana',
        description: 'Zipline, the San Francisco-based UAV manufacturer and logistics services provider, has launched a program in Ghana today for drone delivery of medical supplies. Working with the Ghanaian government, Zipline will operate 30 drones out of four distribution cent…',
        url: 'https://techcrunch.com/2019/04/24/drone-delivery-startup-zipline-launches-uav-medical-program-in-ghana/',
        urlToImage: 'https://techcrunch.com/wp-content/uploads/2019/04/Zipline-Drone-Delivery-2019.jpg?w=711',
        publishedAt: '2019-04-24T10:00:13Z',
        content: 'Zipline, the San Francisco-based UAV manufacturer and logistics services provider, has launched a program in Ghana today for drone delivery of medical supplies.\r\nWorking with the Ghanaian government, Zipline will operate 30 drones out of four distribution cen… [+4072 chars]',
    },
    {
        source: {
            id: 'techcrunch',
            name: 'TechCrunch',
        },
        author: 'Natasha Lomas',
        title: 'UK gives Huawei an amber light to supply 5G',
        description: 'The UK government will allow Huawei to be a supplier for some non-core parts of the country’s 5G networks, despite concerns that the involvement of the Chinese telecoms vendor could pose a risk to national security. But it will be excluded from core parts of …',
        url: 'https://techcrunch.com/2019/04/24/uk-gives-huawei-an-amber-light-to-supply-5g/',
        urlToImage: 'https://techcrunch.com/wp-content/uploads/2019/02/huawei.jpg?w=572',
        publishedAt: '2019-04-24T09:13:35Z',
        content: 'The UK government will allow Huawei to be a supplier for some non-core parts of the country’s 5G networks, despite concerns that the involvement of the Chinese telecoms vendor could pose a risk to national security. But it will be excluded from core parts of … [+5193 chars]',
    },
    {
        source: {
            id: 'techcrunch',
            name: 'TechCrunch',
        },
        author: "Steve O'Hear",
        title: "Holded, the 'business operating system' for SMEs, gets €6M in Series A funding led by Lakestar",
        description: 'Holded, the Barcelona-based startup that offers a SaaS to help SMEs with a range of business tasks, has raised €6 million in Series A funding. The round is led by Lakestar, with previous backers Nauta Capital and Seedrocket 4Founders Capital following on. Fou…',
        url: 'https://techcrunch.com/2019/04/24/holded/',
        urlToImage: 'https://techcrunch.com/wp-content/uploads/2019/04/HOLDED-9668.jpg?w=343',
        publishedAt: '2019-04-24T08:00:01Z',
        content: 'Holded, the Barcelona-based startup that offers a SaaS to help SMEs with a range of business tasks, has raised 6 million in Series A funding. The round is led by Lakestar, with previous backers Nauta Capital and Seedrocket 4Founders Capital following on.\r\nFou… [+1741 chars]',
    },
    {
        source: {
            id: 'techcrunch',
            name: 'TechCrunch',
        },
        author: 'Kate Clark',
        title: 'AV8 Ventures launches with $170M to invest in digital health, mobility and enterprise tech',
        description: 'The fund, headquartered in Palo Alto and London, is backed solely by German insurance business Allianz.',
        url: 'https://techcrunch.com/2019/04/23/av8-ventures-raises-170m-to-invest-in-digital-health-mobility-and-enterprise-tech/',
        urlToImage: 'https://techcrunch.com/wp-content/uploads/2019/04/miles-kirby-george-ugras.jpg?w=764',
        publishedAt: '2019-04-24T06:59:17Z',
        content: 'AV8 Ventures has closed on 150 million (about $170 million) for its debut early-stage venture capital fund to invest in seed and Series A startups in the U.S. and Europe focused on the “machine-enabled future.”\r\nAllianz, a German insurance and asset managemen… [+2690 chars]',
    },
    {
        source: {
            id: 'techcrunch',
            name: 'TechCrunch',
        },
        author: 'Jonathan Shieber',
        title: 'A new Tesla Model S or X can now drive from Los Angeles to San Francisco on a single charge',
        description: 'Tesla has announced that it has extended the range of its Model S vehicle to 370 miles and Model X to 325 miles on a single charge — extending the range of its cars to make the trip from Los Angeles to San Francisco on a single charge.  The extensions beat Te…',
        url: 'https://techcrunch.com/2019/04/23/a-new-tesla-model-s-or-x-can-now-drive-from-los-angeles-to-san-francisco-on-a-single-charge/',
        urlToImage: 'https://techcrunch.com/wp-content/uploads/2018/05/tesla-competitors.jpg?w=753',
        publishedAt: '2019-04-24T02:57:03Z',
        content: 'Tesla has announced that it has extended the range of its Model S vehicle to 370 miles and Model X to 325 miles on a single charge — extending the range of its cars to make the trip from Los Angeles to San Francisco on a single charge. \r\nThe extensions beat T… [+2001 chars]',
    },
    {
        source: {
            id: 'techcrunch',
            name: 'TechCrunch',
        },
        author: 'Connie Loizos',
        title: "The IPO market is heating up again, but it won't change how fast companies go public",
        description: 'It’s been an exciting couple of months for startup employees and public market shareholders alike, as a growing number of brands that have talked about going public for some time are finally marching out the door and, on the whole, receiving enthusiastic rece…',
        url: 'https://techcrunch.com/2019/04/23/the-ipo-market-is-heating-up-again-but-it-wont-change-how-fast-companies-go-public/',
        urlToImage: 'https://techcrunch.com/wp-content/uploads/2019/04/PD-OB-Photo-190411_Press-1-1-1.jpg?w=600',
        publishedAt: '2019-04-24T00:13:01Z',
        content: 'It’s been an exciting couple of months for startup employees and public market shareholders alike, as a growing number of brands that have talked about going public for some time are finally marching out the door and, on the whole, receiving enthusiastic rece… [+6115 chars]',
    },
    {
        source: {
            id: 'techcrunch',
            name: 'TechCrunch',
        },
        author: 'Anthony Ha',
        title: "'Avengers: Endgame' is a very silly movie, but it ends in exactly the right way",
        description: 'With just a few days until the release of “Avengers: Endgame,” Marvel fans everywhere are probably wondering A) Who dies?? and B) Will this actually resolve the cliffhanger ending of “Infinity War” in a satisfying way? So, just to get it out of the way: A) I’…',
        url: 'https://techcrunch.com/2019/04/23/avengers-endgame-review/',
        urlToImage: 'https://techcrunch.com/wp-content/uploads/2019/04/BTP1260_v110.1081.jpg?w=759',
        publishedAt: '2019-04-23T22:41:13Z',
        content: 'With just a few days until the release of “Avengers: Endgame,” Marvel fans everywhere are probably wondering A) Who dies?? and B) Will this actually resolve the cliffhanger ending of “Infinity War” in a satisfying way?\r\nSo, just to get it out of the way: A) I… [+3691 chars]',
    },
    {
        source: {
            id: 'techcrunch',
            name: 'TechCrunch',
        },
        author: 'Taylor Hatmaker',
        title: "Jack Dorsey just met with Trump to talk about the health of Twitter's public discourse",
        description: 'Twitter’s co-founder and CEO historically doesn’t have the most discerning tastes when it comes to who he decides to engage with. Fresh off the podcast circuit, today a thoroughly beardy Jack Dorsey sat down with President Trump for his most high profile tête…',
        url: 'https://techcrunch.com/2019/04/23/jack-dorsey-trump-meeting-twitter/',
        urlToImage: 'https://techcrunch.com/wp-content/uploads/2019/04/GettyImages-1134474984.jpg?w=600',
        publishedAt: '2019-04-23T21:36:09Z',
        content: 'Twitter’s co-founder and CEO historically doesn’t have the most discerning tastes when it comes to who he decides to engage with. Fresh off the podcast circuit, today a thoroughly beardy Jack Dorsey sat down with President Trump for his most high profile tête… [+1158 chars]',
    },
    {
        source: {
            id: 'techcrunch',
            name: 'TechCrunch',
        },
        author: 'Kate Clark',
        title: 'Postmates has launched in 1,000 new cities since December',
        description: 'The on-demand delivery platform is expanding rapidly ahead of its 2019 IPO.',
        url: 'https://techcrunch.com/2019/04/23/postmates-has-launched-in-1000-new-cities-since-december/',
        urlToImage: 'https://techcrunch.com/wp-content/uploads/2019/04/GettyImages-976735324.jpg?w=533',
        publishedAt: '2019-04-23T21:06:19Z',
        content: 'Postmates is expanding like crazy ahead of an initial public offering expected later this year. The food delivery business has launched in 1,000 new cities since December, the company announced today.\r\nSan Francisco-based Postmates now operates its on-demand … [+1685 chars]',
    },
];

export default articles;
