const sources = [
    {
        id: 'abc-news',
        name: 'ABC News',
        description: 'Your trusted source for breaking news, analysis, exclusive interviews, headlines, and videos at ABCNews.com.',
        url: 'https://abcnews.go.com',
        category: 'general',
        language: 'en',
        country: 'us',
    },
    {
        id: 'abc-news-au',
        name: 'ABC News (AU)',
        description: "Australia's most trusted source of local, national and world news. Comprehensive, independent, in-depth analysis, the latest business, sport, weather and more.",
        url: 'http://www.abc.net.au/news',
        category: 'general',
        language: 'en',
        country: 'au',
    },
    {
        id: 'aftenposten',
        name: 'Aftenposten',
        description: 'Norges ledende nettavis med alltid oppdaterte nyheter innenfor innenriks, utenriks, sport og kultur.',
        url: 'https://www.aftenposten.no',
        category: 'general',
        language: 'no',
        country: 'no',
    },
    {
        id: 'blasting-news-br',
        name: 'Blasting News (BR)',
        description: 'Descubra a seção brasileira da Blasting News, a primeira revista feita pelo  público, com notícias globais e vídeos independentes. Junte-se a nós e torne- se um repórter.',
        url: 'http://br.blastingnews.com',
        category: 'general',
        language: 'pt',
        country: 'br',
    },
    {
        id: 'bleacher-report',
        name: 'Bleacher Report',
        description: 'Sports journalists and bloggers covering NFL, MLB, NBA, NHL, MMA, college football and basketball, NASCAR, fantasy sports and more. News, photos, mock drafts, game scores, player profiles and more!',
        url: 'http://www.bleacherreport.com',
        category: 'sports',
        language: 'en',
        country: 'us',
    },
    {
        id: 'bloomberg',
        name: 'Bloomberg',
        description: 'Bloomberg delivers business and markets news, data, analysis, and video to the world, featuring stories from Businessweek and Bloomberg News.',
        url: 'http://www.bloomberg.com',
        category: 'business',
        language: 'en',
        country: 'us',
    },
    {
        id: 'espn',
        name: 'ESPN',
        description: 'ESPN has up-to-the-minute sports news coverage, scores, highlights and commentary for NFL, MLB, NBA, College Football, NCAA Basketball and more.',
        url: 'http://espn.go.com',
        category: 'sports',
        language: 'en',
        country: 'us',
    },
    {
        id: 'independent',
        name: 'Independent',
        description: 'National morning quality (tabloid) includes free online access to news and supplements. Insight by Robert Fisk and various other columnists.',
        url: 'http://www.independent.co.uk',
        category: 'general',
        language: 'en',
        country: 'gb',
    },
];

export default sources;
